source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'

platform :ios, '9.0'

use_frameworks!

target 'x3Note' do
    pod 'RxSwift', :git => 'git@github.com:ReactiveX/RxSwift.git', :tag => '5.1.0'
    pod 'RxCocoa', :git => 'git@github.com:ReactiveX/RxSwift.git', :tag => '5.1.0'
    pod 'RxDataSources'
    pod 'SwiftyBeaver'
    pod 'Haptico' # https://github.com/iSapozhnik/Haptico
    pod 'Drawsana' # https://github.com/Asana/Drawsana
    pod 'SwiftGen', '~> 6.0'
    pod 'KDCalendar', '~> 1.6.5'
    pod 'PKHUD', '~> 5.0'
#    pod 'Firebase/Analytics', :path => '~/Documents/firebase'
#    pod 'ShowTime'
end

target 'x3NoteTests' do
    pod 'RxSwift', :git => 'git@github.com:ReactiveX/RxSwift.git', :tag => '5.1.0'
    pod 'RxCocoa', :git => 'git@github.com:ReactiveX/RxSwift.git', :tag => '5.1.0'
end

target 'Core' do
  pod 'RxSwift', :git => 'git@github.com:ReactiveX/RxSwift.git', :tag => '5.1.0'
  pod 'RxCocoa', :git => 'git@github.com:ReactiveX/RxSwift.git', :tag => '5.1.0'
  pod 'SwiftyBeaver'
  pod 'SwiftyStoreKit', :git => 'git@github.com:bizz84/SwiftyStoreKit.git', :tag => '0.15.1'
  pod 'MHWebViewController'
end

target 'Interface' do
  pod 'RxSwift', :git => 'git@github.com:ReactiveX/RxSwift.git', :tag => '5.1.0'
  pod 'RxCocoa', :git => 'git@github.com:ReactiveX/RxSwift.git', :tag => '5.1.0'
  pod 'SwiftyBeaver'
  pod 'PKHUD', '~> 5.0'
end

target 'CaptureIdeaExtension' do
    pod 'SwiftyBeaver'
end

target 'CaptureActionExtension' do
    pod 'SwiftyBeaver'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        # Fix bundle targets' 'Signing Certificate' to 'Sign to Run Locally'
        if target.respond_to?(:product_type) and target.product_type == "com.apple.product-type.bundle"
            target.build_configurations.each do |config|
                config.build_settings['CODE_SIGN_IDENTITY[sdk=macosx*]'] = '-'
            end
        end
    end
end
