# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  lane :create_app do
    produce(
      app_name: "Iceberg",
      language: "English",
      app_version: "0.1",
      sku: "iceberg",
    )
  end

  lane :upload do
    
  end

  lane :metadata do
    
  end

  lane :scrrend_shot do

  end

  lane :test do
    scan(
      workspace: 'Iceberg.xcworkspace',
      devices: ['iPhone XS', 'iPhone 8']
    )
  end
end
