# This file contains the fastlane.tools configuration 
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

ENV["SPACESHIP_2FA_SMS_DEFAULT_PHONE_NUMBER"]="+8618190768602";

default_platform(:ios)

platform :ios do

  lane :create_app do
    produce(
      app_name: "x3 Note",
      app_identifier: "com.wod.x3note",
      language: "English",
      app_version: "1.0",
      sku: "x3note",
    )
  end

  lane :beta do
    increment_build_number

    cert(development: false, generate_apple_certs: true)
    sigh(app_identifier: "com.wod.x3note", development: false, force: false)
    sigh(app_identifier: "com.wod.x3note.CaptureIdeaExtension", development: false, force: false)
    sigh(app_identifier: "com.wod.x3note.CaptureActionExtension", development: false, force: false)
    
   # sigh(app_identifier: "com.wod.x3note", development: false, force: false, platform: macos)
   #  sigh(app_identifier: "com.wod.x3note.CaptureIdeaExtension", development: false, force: false, platform: macos)
   #  sigh(app_identifier: "com.wod.x3note.CaptureActionExtension", development: false, force: false, platform: macos)

    build()
    upload_testflight()
  end

  lane :build do
    gym(
      scheme: "x3Note",
      workspace: "x3Note.xcworkspace",
      catalyst_platform: 'ios',
      clean: true,
      export_method: "app-store",
    )



#    gym(
#      scheme: "x3Note",
#      workspace: "x3Note.xcworkspace",
#      catalyst_platform: 'macos',
#      clean: true,
#      export_method: "app-store",
#    )

  end

  lane :upload_testflight do
    upload_to_testflight
  end

  lane :upload do
    
  end

  lane :metadata do
    deliver(
      submit_for_review: false,
      automatic_release: false,
      skip_screenshots: true,
      skip_binary_upload: true
    )
  end

  lane :metadata_mac do
    deliver(
      platform: 'osx',
      submit_for_review: false,
      automatic_release: false,
      skip_screenshots: true,
      skip_binary_upload: true
    )
  end


  lane :metadata_with_images do
    deliver(
      submit_for_review: false,
      automatic_release: false,
      skip_screenshots: false,
      skip_binary_upload: true
    )
  end

  lane :metadata_mac_with_images do
    deliver(
      platform: 'osx',
      submit_for_review: false,
      automatic_release: false,
      skip_screenshots: false,
      skip_binary_upload: true
    )
  end

  lane :scrrend_shot do

  end

  lane :test do
    scan(
      workspace: 'x3Note.xcworkspace',
      devices: ['iPhone XS', 'iPhone 8']
    )
  end
end
