platform :ios, '9.0'

use_frameworks!

target 'Iceland' do
#    pod 'RxSwift'
#    pod 'RxCocoa'
    pod 'SwiftyBeaver'
#    pod 'Result'
    pod 'Haptico' # https://github.com/iSapozhnik/Haptico
    pod 'Drawsana' # https://github.com/Asana/Drawsan
    pod 'SwiftGen', '~> 6.0'
    pod 'KDCalendar', '~> 1.6.5'
end

target 'IcelandTests' do
    pod 'RxSwift'
    pod 'RxCocoa'
end

target 'Business' do
    pod 'SwiftyBeaver'
#    pod 'Result'
end

target 'Interface' do
    pod 'SwiftyBeaver'
end
