platform :ios, '9.0'

use_frameworks!

target 'Iceland' do
    pod 'RxSwift'
    pod 'RxCocoa'
    pod 'SwiftyBeaver'
    pod 'Result'
    pod 'Haptico' # https://github.com/iSapozhnik/Haptico
    pod 'Drawsana' # https://github.com/Asana/Drawsan   a
    pod 'SwiftGen', '~> 6.0'
    pod 'JTAppleCalendar', '~> 7.0'
end

target 'IcelandTests' do
    pod 'RxSwift'
    pod 'RxCocoa'
end

target 'Business' do
    pod 'SwiftyBeaver'
    pod 'Result'
end

target 'Storage' do
   pod 'KeychainAccess'
end
