* 编辑器
目标是打造一个专业好用的编辑器。现有的功能包括基本的文字编辑，富文本标记，添加各种附件等基本功能。更多功能将会陆续提供。
** 标记
支持粗体，下划线，删除线，斜体，高亮效果。
** 附件
- 图片
- 涂鸦
- 视频
- 音频
- 位置
- 链接
** 插入灵感
除文字以外的灵感，会作为附件插入到文档中。
** 段落管理
段落支持标签，状态和优先级。可以移动整个段落，对段落的层次进行调整。段落可以添加子段落。
*** 标签
文档内的段落可以添加多个标签。
*** 状态
为段落设置是否完成的状态。
*** 优先级
优先级会影响在日程表中的位置，优先级越高会显示在越靠山的位置。
** 导出
将整个文档导出为 html, txt, pdf, jpe 等格式，并保存或者分享。
** 折叠
包含正文或者子段落的段落可以折叠为一行标题。
** 移动
*** 段落标题
通过移动标题调整段落的层次和位置。
1. 左右移动进行层次调整
2. 上下移动进行同级的段落的位置调整。
*** 段落正文
进行当前所在行文字的缩进和位置调整。
1. 左右移动增加/减少缩进。
2. 上下移动在当前段落内移动当前行的文字。
** 整理段落
可以在当前文档，或者其他任意文档中，选择一个位置，将当前的段落移动过去。移动过去的目标可以是一个段落，或者是文档的开始，或者结尾。
如果移动过去的位置是一个段落，移动之后将会成为这个段落的子段落。
* 素材采集
** 应用内采集
应用内所有界面都可以直接进入素材采集入口。除了编辑器外都在右下角的按钮，编辑器在右上角动作按钮内。
** 应用外分享
所有具有分享工功能的应用都可以把内容分享给 x3 笔记，分享的内容将被放入采集的灵感库内。
** 分配
从灵感采集库中，可以选直接将里灵感放到文档中。
* 日程管理
文档内容可以被显示在日程表中进行工作管理。
** 日程表
文档中，段落可以加上日期和状态。
带有日期和状态的段落标题会显示在日程表中。
* 内容管理
** 快捷列表
通过标签，状态，日程表来对文档的标题进行分类和快捷访问。
** 子文档
每个文档都可以创建不限个数，不限层数的子文档。
** 移动文件
移动文档其他文档位置作为子文档，或者移动到最外层作为最上层文档。
** 封面
每个文档可以设置和修改封面。
** 复制
在当前位置创建一个内容一样的新文档。
** 导入
通过其他文档导入到 x3 笔记中创建新的文档。
** iCloud 同步
使用 iCloud 账户登陆需要同步的设备，自动同步所有文件。
