* TODO 开始编辑
x3 笔记使用类 Markdown 的语法，支持富文本标签，列表，复选框，引用块，代码块，插入多种附件。
#date#
** 段落
将所有内容都放在段落中，是一个好习惯，因为段落支持标签，移动，状态，优先级，可以折叠，可以进行日程管理，等等。
不过如果不使用段落，也没有问题，整个笔记是基于文本的结构，可以记录任何文字数据，可以自由导入导出，也可以通过文件直接拖拽，管理内容，比如在打开 iCloud 的时候，可以在*文件*应用中管理自己的笔记的所有文件。

点击*标题*按钮，创建一个标题。标题按钮是最常用的一个按钮之一，图标为一个大写的*H*。
** 折叠
段落如果包含正文内容，就可以折叠成一行标题。
** 附件
x3 笔记支持包括图片，音频，视频，链接，位置多种附件。
* 灵感
灵感是各种素材的统称，通过各种附件的形式，进行统一管理，然后在需要的时候移到文档中。
** 采集，以后再整理
在使用 x3 笔记的时候，不管在什么界面，都可以找到抓取灵感的按钮。一般情况下都在屏幕右下角，编辑器中，在右上方动作栏内。
通过多种方式采集的灵感，统一放置在已采集的灵感内。
** 分享到 x3 笔记
其他应用的内容可以通过分享将内容分享到 x3 笔记笔记，分享的内容也会作为灵感放在已采集的灵感中。
* 安排日程
段落在添加了状态，或者日期之后，会出现在日程表上，从而成为一个日程上的条目。
** 状态
状态分为两种，已完成和未完成。
两种状态都有自带的不同选择，比如TODO, DONE, CANCEL 这些是自带的状态，你可以根据习惯和需要，添加使用自定义状态。
** 日期
日期有三种。
1. 指定日期
只有到了指定日期，对应的段落标题才会出现在日程表上。
2. 开始日期
在接近开始日期，就会出现在日程表上，如果没有更改状态为已完成，会一直保留在日程表。
3. 截止日期
与开始日期类似，会在接近截止日出现在日程表，并且保留知道状态变成已完成。
** 优先级
优先级会影响在日程表上的位置。含有优先级的段落会显示在不含优先级之前，高优先级会显示在低优先级之前。
* 整理
** 子文件
任何文件都可以建立任意个数，任意层深度的子文件。
** 标签
段落可以使用便签进行分类。子段落会继承父段落的标签。
** 移动
- 文件可以移动成为其他文件的子文件。
- 段落可以在文段内，以及文档之间自由移动。
** 保存到 iCloud
如果将文件保存位置选择为 iCloud，所有文件则可以自动同步和保存到 iCloud 仓库，如果选择保存在本地，则只会保存在当前的设备上。
