* Editor
Nebula's goal is to build a professional, comfortable to use editor, provides functions like basic text editing, rich text marks, insert multiple types of attachments, etc. And many more to be added.
** Text marks
Supports *Bold*, _Underscore_, /Italic/, and ~Highlight~ effects.
** Attachment
- Image
- Sketch
- Video
- Audio
- Location
- Link
** Capture ideas
Inspiration ideas other than text, will be inserted as attachments.
** Paragraph management
Paragraph can attach tag, status and priority to them, those are tools to help do task management and organize your contents.
And you can use move paragraph to rearrange you contents, or modify the level of the paragraph.
*** Tag
Organize paragraphs with tags.
*** Status
To indicate the work progress of the whatever you want to add to the paragraph, and also control if the paragraph shows in *Agenda*.
*** Priority
Priority will affect the position of paragraph in *Agenda*, higher priority will show before lower priority.
** Export
You can export document as /HTML/, /TXT/, /PDF/, /JPG/ files.
** Folding
Any paragraph containing characters below heading, can be folded.
** Move
*** Move paragraph heading
When you move at paragraph heading, you are moving the whole paragraph.
1. Move left and right to modify the level of the paragraph.
2. Move up and down to adjust the order of the same level paragraphs.
*** Paragraph content
When moving at paragraph content, you are moving the current line of text.
1. Move left and right to decrease and increase indent.
2. Move up and down to switch position of the line right above or below.
** Organize paragraphs
You can move a paragraph to another paragraph, as its sub paragraph, or move to beginning/ending of the document, and keeping the paragraph level, and the move can be inside one documents, or to another document.
* Capture inspiration
** Inside Nebula
You access *Capture inspiration* at every page inside Nebula. When you are editing a document, you can find it by tapping the action button, other places, the button is floating at bottom right bottom of the screen.
** Share to Nebula
Any app that can share content, can share to Nebula, and kept in *Ideas*
** Refile
When you are managing the captured ideas, you can choose a place, then move that idea to the place of document you choose.
* Agenda management
Contents of documents, can be managed on *Agenda*.
** Agenda
In documents, you can add *Date and time*, or *Statue* to paragraph. those paragraph will be shown on *Agenda*
* Content management
** Agenda shortcut
According to *tags*, *status*, *date and time* to categorize and fast access contents of your documents.
** Sub document
Each document can create sub documents.
** Move documents
You can move document to another document as it subdocument, or move to top folder, to become top level document.
** Cover
You can choose an image as the cover of a document.
** Duplicate
Make a copy of the chosen document.
** Import
Import other file into Nebula, use its content to create a new document, now we support *org* file, if you want to import a org file to Nebula, you can open it with Nebula, or share to Nebula.
** iCloud synchornize
Save you document on iCloud, then it will synchronize across all your devices, free of charge.
